# Generated by Django 3.2.18 on 2024-12-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('qnt', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
