# Generated by Django 3.2.18 on 2024-12-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='tot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
