# Generated by Django 3.2.18 on 2024-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241206_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=6)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
